name: flutter_braintree
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 0.1.1
author: Julien Scholz <julienscholzo@hotmail.de>
homepage: https://github.com/Pikaju/FlutterBraintree

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutter_braintree
    pluginClass: FlutterBraintreePlugin